export enum EPS {
  SANITAS = "Sanitas",
  NUEVA_EPS = "Nueva EPS",
  SALUD_TOTAL = "Salud Total",
  SURA = "Sura",
  COMPENSAR = "Compensar",
  FAMISANAR = "Famisanar",
  COOSALUD = "Coosalud",
  MUTUAL_SER = "Mutual Ser",
  SAVIA_SALUD = "Savia Salud",
  CAPITAL_SALUD = "Capital Salud",
  ASMET_SALUD = "Asmet Salud",
  ECOOPSOS = "Ecoopsos",
  EMSSANAR = "Emssanar",
  CAJACOPI = "Cajacopi",
  COMFENALCO_ANTIOQUIA = "Comfenalco Antioquia",
  COMFACHOCO = "Comfachocó",
  COMPARTA = "Comparta",
  DUSAKAWI = "Dusakawi",
  MALLAMAS = "Mallamas",
  ANAS_WAIMAS = "Anas Wayuu"
}
