export enum TipoMaquinaria {
  CORTASETOS_MANO = 'cortasetos_mano',
  CORTASETOS_ALTURA = 'cortasetos_altura',
  GUADANIA = 'guadania',
  PODADORA_CESPED = 'podadora_cesped',
  ESCALERA = 'escalera',
  SOPLADORA = 'sopladora',
  FUMIGADORA_MOTOR = 'fumigadora_motor',
  BOMBA_ESPALDA = 'bomba_espalda',
  MOTOSIERRA_MANO = 'motosierra_mano',
  MOTOSIERRA_ALTURA = 'motosierra_altura',
  HIDROLAVADORA_ELECTRICA = 'hidrolavadora_electrica',
  HIDROLAVADORA_GASOLINA = 'hidrolavadora_gasolina',
  PULIDORA = 'pulidora',
  TALADRO = 'taladro',
  ROTOMARTILLO = 'rotomartillo',
  LAVABRILLADORA = 'lavabrilladora',
  COMPRESOR = 'compresor',
  PULVERIZADORA_PINTURA = 'pulverizadora_pintura',
  EQUIPO_ALTURAS = 'equipo_alturas',
  MEDIA_LUNA = 'media_luna',
  CAJA_HERRAMIENTAS = 'caja_herramientas',
  OTRO = 'otro'
}
